---
title: "Vis for March team meeting"
author: '`r Sys.getenv("USER")`'
date: '`r format(Sys.time(), "%d %B, %Y")`' 
always_allow_html: true
output: 
  github_document:
    keep_html: true
---
	
```{r setup, include = FALSE}
file_name <- rstudioapi::getSourceEditorContext()$path

knitr::opts_chunk$set(
  fig.path =
    paste0("figures/", sub("\\.Rmd$", "", basename(file_name)), "/", sep = "")
)

ggplot2::theme_set(ggplot2::theme_classic(base_size = 10))
```

```{r packages, message=FALSE, warning=FALSE}
library("tidyverse")
library("here")
```

```{r}
models_out <- readRDS(here("data", "derived", "all_runs.rds")) %>% 
  filter(n_train != 31)
```

```{r}
plot_real_pred <- function(out, study_condition_val, study_condition,
                           max_col) {
  
  out %>%  
    filter((!!as.name(study_condition)) == study_condition_val) -> out_subset
  
  out_subset %>% 
    unnest(df_out) %>% 
    mutate(error = abs(cate_pred - cate_real)) %>% 
    ggplot(aes(x = cate_real, y = cate_pred, colour = error)) +
    geom_hline(yintercept = 0, colour = "grey", linetype = 2) +
    geom_vline(xintercept = 0, colour = "grey", linetype = 2) +
    geom_point() +
    geom_abline(intercept = 0, slope = 1, colour = "blue") +
    scale_color_gradient(low = "lightblue", high = "red3",
                         limits = c(0, max_col)) +
    xlim(-35, 35) +
    ylim(-35, 35) +
    theme_classic(base_size = 15) +
    ggtitle(paste(study_condition,  study_condition_val, sep = " = ")) +
    facet_wrap(~ learner) 
}
```

## ntrain 

```{r fig.height=5, fig.width=13, warning=FALSE}

models_out %>% 
  filter(assignment == "random",
         var_omit == FALSE,
         prop_not_treated == 0.5,
         test_plot_location == "random"
         ) -> n_train_df

map(.x = c(62, 125, 250, 500, 1000), 
    .f = plot_real_pred, 
    study_condition = "n_train", 
    out = n_train_df,
    max_col = 40)

```

## prop treated

```{r fig.height=5, fig.width=13, warning=FALSE}

models_out %>% 
  filter(assignment == "random",
         var_omit == FALSE,
         n_train == 1000,
         test_plot_location == "random"
         ) -> prop_not_treat_df

map(.x = c(0.3, 0.5, 0.7), 
    .f = plot_real_pred, 
    study_condition = "prop_not_treated", 
    out = prop_not_treat_df,
    max_col = 40)
```

## treat assignment

```{r fig.height=5, fig.width=13, warning=FALSE}

models_out %>% 
  filter(prop_not_treated == 0.5,
         var_omit == FALSE,
         n_train == 1000,
         test_plot_location == "random"
         ) -> prop_not_treat_df

map(.x = c("random", "correlated_altitude", "correlated_region"), 
    .f = plot_real_pred, 
    study_condition = "assignment", 
    out = prop_not_treat_df,
    max_col = 40)
```

## var ommission

```{r fig.height=5, fig.width=13, warning=FALSE}

models_out %>% 
  filter(assignment == "random",
         prop_not_treated == 0.5,
         n_train == 1000,
         test_plot_location == "random"
         ) -> var_omit_df

map(.x = c(TRUE, FALSE), 
    .f = plot_real_pred, 
    study_condition = "var_omit", 
    out = var_omit_df,
    max_col = 40)
```

## test plot location

```{r fig.height=5, fig.width=13, warning=FALSE}

models_out %>% 
  filter(assignment == "random",
         prop_not_treated == 0.5,
         n_train == 1000,
         var_omit == FALSE
         ) -> test_loc_df

map(.x = c("random", "edge", "centre"), 
    .f = plot_real_pred, 
    study_condition = "test_plot_location", 
    out = test_loc_df,
    max_col = 40)
```
