---
title: "New layered vis"
author: '`r Sys.getenv("USER")`'
date: '`r format(Sys.time(), "%d %B, %Y")`' 
always_allow_html: true
output: 
  github_document:
    keep_html: true
---
	
```{r setup, include = FALSE}
file_name <- rstudioapi::getSourceEditorContext()$path

knitr::opts_chunk$set(
  fig.path =
    paste0("figures/", sub("\\.Rmd$", "", basename(file_name)), "/", sep = "")
)

ggplot2::theme_set(ggplot2::theme_classic(base_size = 10))
```

```{r packages, message=FALSE, warning=FALSE}
library("tidyverse")
library("here")
library("patchwork")
library("viridis")

set.seed(123)
```

```{r}
models_out <- readRDS(here("data", "derived", "models_out.rds"))
```

## Function to colour by error

```{r}
plot_real_pred <- function(out, study_condition_val, study_condition) {
  
  out %>%  
    filter((!!as.name(study_condition)) == study_condition_val) -> out_subset
  
  lookup <- c(cate_pred = "cate_s_learn", 
              cate_pred = "cate_t_learn", 
              cate_pred = "cate_x_learn")
  
  out_subset[["df_out"]] <- 
    map(out_subset[["df_out"]], ~ rename(.x, any_of(lookup)))
  
  out_subset %>% 
    unnest(df_out) %>% 
    ggplot(aes(x = cate_real, y = cate_pred, colour = abs(diff))) +
    geom_hline(yintercept = 0, colour = "grey", linetype = 2) +
    geom_vline(xintercept = 0, colour = "grey", linetype = 2) +
    geom_point() +
    geom_abline(intercept = 0, slope = 1, colour = "blue") +
    scale_color_gradient(low = "lightblue", high = "red3",
                         limits = c(0, 35)) +
    xlim(-35, 35) +
    ylim(-35, 35) +
    theme_classic(base_size = 15) +
    ggtitle(paste(study_condition,  study_condition_val, sep = " = ")) +
    facet_wrap(~ learner) 
}


```

```{r fig.height=5, fig.width=13, warning=FALSE}

map(.x = c(200, 400, 800, 1400), 
    .f = plot_real_pred, 
    study_condition = "n_train", 
    out = models_out)

```

## Function to layer and colour by the same "study condition"

```{r warning=FALSE}
plot_real_pred_layer <- function(out, study_condition_val, study_condition, pal) {
  
  out %>%  
    filter((!!as.name(study_condition)) %in% study_condition_val) -> out_subset
  
  lookup <- c(cate_pred = "cate_s_learn", 
              cate_pred = "cate_t_learn", 
              cate_pred = "cate_x_learn")
  
  out_subset[["df_out"]] <- 
    map(out_subset[["df_out"]], ~ rename(.x, any_of(lookup)))
  
  out_subset %>% 
    unnest(df_out) %>% 
    ggplot(aes(x = cate_real, y = cate_pred, colour = as.factor(!!as.name(study_condition)))) +
    geom_hline(yintercept = 0, colour = "grey", linetype = 2) +
    geom_vline(xintercept = 0, colour = "grey", linetype = 2) +
    geom_point(shape = 16, alpha = 0.7) +
    geom_abline(intercept = 0, slope = 1, colour = "red") +
    scale_colour_manual(values = pal, name = paste(study_condition)) +
    xlim(-40, 40) +
    ylim(-40, 40) +
    theme_classic(base_size = 15) +
    theme(legend.position = "top", legend.justification = "left") +
    facet_wrap(~ learner) 
  
}
```

```{r fig.height=5, fig.width=13, warning=FALSE}

map(
  .x = list(c(200), c(200, 400), c(200, 400, 800), c(200, 400, 800, 1400)),
  .f = plot_real_pred_layer,
  pal = c(
    "1400" = viridis(4)[[1]],
    "800" = viridis(4)[[2]],
    "400" = viridis(4)[[3]],
    "200" = viridis(4)[[4]]
  ),
  study_condition = "n_train",
  out = models_out
)

```

## Funciton to keep n_train coloured, with shape and layer by a different study condition

```{r warning=FALSE}
plot_real_pred_layer_shape <- function(out, study_condition_val, study_condition) {
  
  out %>%  
    filter((!!as.name(study_condition)) %in% study_condition_val) -> out_subset
  
  lookup <- c(cate_pred = "cate_s_learn", 
              cate_pred = "cate_t_learn", 
              cate_pred = "cate_x_learn")
  
  out_subset[["df_out"]] <- 
    map(out_subset[["df_out"]], ~ rename(.x, any_of(lookup)))
  
  out_subset %>% 
    unnest(df_out) %>% 
    ggplot(aes(x = cate_real, y = cate_pred, colour = as.ordered(n_train), shape = !!as.name(study_condition))) +
    geom_hline(yintercept = 0, colour = "grey", linetype = 2) +
    geom_vline(xintercept = 0, colour = "grey", linetype = 2) +
    geom_point(alpha = 0.7) +
    geom_abline(intercept = 0, slope = 1, colour = "red") +
    scale_colour_viridis_d(name = "n_train") +
    xlim(-40, 40) +
    ylim(-40, 40) +
    theme_classic(base_size = 15) +
    theme(legend.position = "top", legend.justification = "left") +
    facet_wrap(~ learner) 
}

```

### Treatment assignment

```{r fig.height=5, fig.width=13, warning=FALSE}

map(
  .x = list(c("random"), 
            c("random", "blocked_ordered"), 
            c("random", "blocked_ordered", "blocked_random"), 
            c("random", "blocked_ordered", "blocked_random", "correlated_altitude")),
  .f = plot_real_pred_layer_shape,
  study_condition = "assignment",
  out = models_out
)

```

### Test data, in or out?

```{r fig.height=5, fig.width=13, warning=FALSE}

map(
  .x = list(c(TRUE), 
            c(TRUE, FALSE)),
  .f = plot_real_pred_layer_shape,
  study_condition = "random_test_plots",
  out = models_out
)

```
