---
title: "Treat assign"
author: 'eleanorjackson'
date: '`r format(Sys.time(), "%d %B, %Y")`' 
always_allow_html: true
output: 
  github_document:
    keep_html: true
---
	
```{r setup, include = FALSE}
file_name <- rstudioapi::getSourceEditorContext()$path

knitr::opts_chunk$set(
  fig.path =
    paste0("figures/", sub("\\.Rmd$", "", basename(file_name)), "/", sep = "")
)

ggplot2::theme_set(ggplot2::theme_classic(base_size = 15))
```

```{r}
library("tidyverse")
library("here")
library("patchwork")
```

```{r}
results <- 
  readRDS(here::here("data", "derived", "results.rds")) %>% 
  filter(n_train == 1000, 
         assignment == "random", 
         test_plot_location == "stratified",
         var_omit == "none") %>% 
  mutate( learner = recode_factor(
      learner,
      s = "S",
      t = "T",
      x = "X",
      dr = "DR",
      .ordered = TRUE
    ))
```

```{r}
mean_sd <- function(x) {
  data.frame(
    y = mean(x, na.rm = TRUE),
    ymin = mean(x, na.rm = TRUE) - sd(x, na.rm = TRUE),
    ymax = mean(x, na.rm = TRUE) + sd(x, na.rm = TRUE)
  )
}
```


```{r}
results %>%
      ggplot(aes(x = prop_not_treated, y = autoc)) +
      stat_summary(fun.data = mean_sd,
                   geom = "line",
                   linewidth = 0.3) +
      stat_summary(
        fun.data = mean_sd,
        geom = "pointrange",
        size = 0.5,
        fill = "white",
        shape = 21,
        stroke = 0.5,
        linewidth = 0.5
      ) +
      scale_x_continuous(breaks = c(0.3, 0.5, 0.7)) +
  labs(y = "Targeting error\n(1- normalised AUTOC)",
       x = "Treatment imbalance") +
      theme_bw(base_size = 10) +
  facet_grid(~learner) +
  results %>%
      ggplot(aes(x = prop_not_treated, y = rmse)) +
      stat_summary(fun.data = mean_sd,
                   geom = "line",
                   linewidth = 0.3) +
      stat_summary(
        fun.data = mean_sd,
        geom = "pointrange",
        size = 0.5,
        fill = "white",
        shape = 21,
        stroke = 0.5,
        linewidth = 0.5
      ) +
      scale_x_continuous(breaks = c(0.3, 0.5, 0.7))  +
  labs(y = "Estimation error\n(RMSE)",
       x = "Treatment imbalance") +
      theme_bw(base_size = 10) +
  facet_grid(~learner) +
  plot_layout(ncol =1)
```

